apiVersion: v2
name: tenant
description: A Helm chart for deploying managed tenants
type: application
version: 0.0.0
appVersion: "0.1.0"
dependencies:
  - name: lib
    version: "0.0.0"
    repository: "file://../lib"