apiVersion: v2
name: postgres
description: A Helm chart for deploying a managed Postgres database using Crunchy Data Postgres Operator
type: application
version: 0.1.0
appVersion: "16.1.0"
dependencies:
  - name: lib
    version: "0.0.0"
    repository: "file://../lib"
